// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentTask2.Data;

#nullable disable

namespace TechnicalAssessmentTask2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssessmentTask2.Models.SurveyResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HowLineSight1")
                        .HasColumnType("int");

                    b.Property<int?>("HowRoleClarity1")
                        .HasColumnType("int");

                    b.Property<int?>("HowSenseDirection1")
                        .HasColumnType("int");

                    b.Property<int?>("HowSenseProgress1")
                        .HasColumnType("int");

                    b.Property<int?>("HowSystemTools1")
                        .HasColumnType("int");

                    b.Property<int?>("HowSystemTools2")
                        .HasColumnType("int");

                    b.Property<int?>("HowSystemTools3")
                        .HasColumnType("int");

                    b.Property<int?>("HowSystemTools4")
                        .HasColumnType("int");

                    b.Property<string>("LeadershipLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manager")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OutcomeAdvocacy1")
                        .HasColumnType("int");

                    b.Property<int?>("OutcomeDiscretionaryEffort1")
                        .HasColumnType("int");

                    b.Property<int?>("OutcomeIntentToStay1")
                        .HasColumnType("int");

                    b.Property<int>("RespondentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tenure")
                        .HasColumnType("decimal(18,1)");

                    b.Property<int?>("WhatCompensationBenefits1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety2")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety3")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety4")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety5")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety6")
                        .HasColumnType("int");

                    b.Property<int?>("WhatPsychologicalSafety7")
                        .HasColumnType("int");

                    b.Property<int?>("WhatRecognition1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatTalentDevelopment1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatTalentDevelopment2")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkCulture1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkCulture2")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkCulture3")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkCulture4")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkCulture5")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkLifeBalance1")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkLifeBalance2")
                        .HasColumnType("int");

                    b.Property<int?>("WhatWorkLifeBalance3")
                        .HasColumnType("int");

                    b.Property<int?>("WhoFaithLeadership1")
                        .HasColumnType("int");

                    b.Property<int?>("WhoFaithLeadership2")
                        .HasColumnType("int");

                    b.Property<int?>("WhoFaithLeadership3")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship1")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship2")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship3")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship4")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship5")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship6")
                        .HasColumnType("int");

                    b.Property<int?>("WhoRelationship7")
                        .HasColumnType("int");

                    b.Property<int?>("WhoSenseBelonging1")
                        .HasColumnType("int");

                    b.Property<int?>("WhoTrust1")
                        .HasColumnType("int");

                    b.Property<int?>("WhoTrust2")
                        .HasColumnType("int");

                    b.Property<int?>("WhoTrust3")
                        .HasColumnType("int");

                    b.Property<int?>("WhyMeaningfulness1")
                        .HasColumnType("int");

                    b.Property<int?>("WhyMeaningfulness2")
                        .HasColumnType("int");

                    b.Property<int?>("WhyPride1")
                        .HasColumnType("int");

                    b.Property<int?>("WhyPride2")
                        .HasColumnType("int");

                    b.Property<int?>("WhySense1")
                        .HasColumnType("int");

                    b.Property<int?>("WhySense2")
                        .HasColumnType("int");

                    b.Property<int?>("WhySense3")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SurveyResponses", (string)null);
                });

            modelBuilder.Entity("TechnicalAssessmentTask2.Models.TextAnalysis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("OpenEndedAnythingElse1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenEndedContinue1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenEndedStart1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenEndedStop1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SurveyID")
                        .IsUnique();

                    b.ToTable("TextAnalyses", (string)null);
                });

            modelBuilder.Entity("TechnicalAssessmentTask2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechnicalAssessmentTask2.Models.TextAnalysis", b =>
                {
                    b.HasOne("TechnicalAssessmentTask2.Models.SurveyResponse", "SurveyResponse")
                        .WithOne()
                        .HasForeignKey("TechnicalAssessmentTask2.Models.TextAnalysis", "SurveyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveyResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
